- name: Azure Pipelines Action
  uses: Azure/pipelines@v1
  with:
    # Fullyqualified URL to the Azure DevOps organization along with project name(eg, https://dev.azure.com/organization/project-name or https://server.example.com:8080/tfs/DefaultCollection/project-name)
    azure-devops-project-url: https://dev.azure.com/ahold/Ahold-POC
    # Name of the Azure Pipline to be triggered
    azure-pipeline-name: jpetstore-github
    # Paste personal access token of the user as value of secret variable:AZURE_DEVOPS_TOKEN
    azure-devops-token: owqi3z4xb5g2kne5ydam2um3ti4avhkjc5qgpw645e326irkfp4q
