#Java
#Checkout,Codescan,QualityCheck,Build,UploadArtifacts and Deploy To Webapp
name: $(build.sourceBranchName)-$(Date:yyyyMMdd)$(Rev:.r)
trigger:
  batch: true
  branches:
    include:
    - master/*
    exclude:
    - '*'
  paths:
    exclude:
    - README.md
pr:
  branches:
    include:
    - '*'
    exclude:
    - 'refs/tags/*'
variables:
  sonarServiceConnection: 'sonar-ahold'
  sonarProjectKey: 'jpetstore'
  sonarProjectName: 'jpetstore'
  sonarSources: '.'
  sonarJavaSource: '.'
  sonarJavaBinaries: '.'
  sonar.verbose: 'true'
  sonar.branch: 'master'
  # Agent VM image name
  vmImageName: 'ubuntu-latest'
  #Build Artifacts
  publishesArtifactsPath: '/home/vsts/work/1/s/target/'
  artifactsPath: '/home/vsts/work/1/s/target/jpetstore.war'
  artifactRepoName: 'jpetstore'
  artifactVersionType: 'patch'
  webServer: 'java-sample-demo11'
  azureServiceConnectionId: 'ahold-poc-demo2'
  azureArtifactName: 'jpetstore'
  azureFeedPublishName: 'bed25be9-4b19-4d72-bd95-49459092e4eb'
stages:
- stage: JavaBuildPipeline
  displayName: Java CI CD Build Pipeline
  jobs:  
  - job: JavaBuildPipeline
    displayName: Java CI CD Build Pipeline
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: SonarQubePrepare@4
      displayName: SonarqubeInitial
      inputs:
        SonarQube: $(sonarServiceConnection)
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: $(sonarProjectKey)
        cliProjectName: $(sonarProjectName)
        cliSources: $(sonarSources)
        extraProperties: |
          sonar.java.source=$(sonarJavaSource)
          sonar.java.binaries=$(sonarJavaBinaries)
    - task: SonarQubeAnalyze@4
      displayName: SonarAnalysis
    - task: SonarQubePublish@4
      displayName: SonarCodeQualityCheck
      inputs:
        pollingTimeoutSec: '300'
    - task: Maven@3
      displayName: BuildWithMaven
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
